import type { Metadata } from "next";
import PolicyPage from "@/components/PolicyPage";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms governing use of the JasonPro Solutions website, enquiries, accounts and service information." };

export default function TermsPage(){return <PolicyPage title="Terms of Use" updated="20 August 2026" summary="These terms govern use of the JasonPro Solutions website and explain the status of enquiries, quotations, project information, digital content and client-account features." sections={[
  {title:"Website purpose",paragraphs:["The website presents JasonPro Solutions capabilities, selected work, information resources and ways to request services. Content is provided for general business information and does not by itself create a client engagement or guarantee availability, price, timeline or outcome."]},
  {title:"Enquiries and quotations",paragraphs:["Submitting a project brief, quote request or consultation request is an invitation to discuss work, not an acceptance of a contract. A project becomes binding only when the parties agree the scope, price, responsibilities and other applicable terms in writing."],bullets:["Quotations depend on the accuracy and completeness of the information supplied.","Material scope changes may require revised pricing or timelines.","JasonPro may decline work that cannot be delivered responsibly, lawfully or within available capacity."]},
  {title:"Client responsibilities",paragraphs:["Clients are responsible for providing accurate information, timely approvals and materials they are entitled to use. Delays in content, access, decisions or feedback can affect delivery dates."],bullets:["Provide lawful and accurate content, data and instructions.","Confirm required stakeholders and approval authority.","Review proofs, designs and deliverables within agreed review periods.","Maintain secure access to their own accounts and credentials."]},
  {title:"Intellectual property",paragraphs:["Ownership and licence terms for commissioned work should be defined in the applicable quotation, proposal or project agreement. Pre-existing JasonPro tools, reusable components, methods, know-how and third-party materials remain subject to their existing ownership or licence terms unless expressly agreed otherwise.","Clients should not assume that editable source files, software source code, third-party fonts, stock assets or licensed materials transfer automatically unless the project agreement states that they do."]},
  {title:"Portfolio and public references",paragraphs:["JasonPro will not knowingly publish confidential client information. Public portfolio use, project screenshots or client references should respect confidentiality obligations and any specific written restrictions agreed for the project."]},
  {title:"Availability and external services",paragraphs:["Websites and systems may rely on third-party hosting, domains, databases, APIs, payment providers, email services or other infrastructure. JasonPro cannot guarantee uninterrupted operation of independent third-party services but will design and configure integrations with reasonable care where they form part of the agreed scope."]},
  {title:"Acceptable use",paragraphs:["You must not use the website, client portal or connected services to attack systems, bypass access controls, upload malicious material, infringe rights, impersonate others or carry out unlawful activity."]},
  {title:"Limitation and governing context",paragraphs:["Nothing on this website should be read as a promise of a specific commercial result unless that result is expressly guaranteed in a written agreement. Project-specific liability, warranties and remedies should be addressed in the applicable agreement. These website terms are intended to operate subject to applicable laws of Botswana."]},
  {title:"Contact",paragraphs:["Questions about these terms can be sent to Marupingjason@gmail.com or directed to JasonPro Solutions in Gaborone, Botswana."]},
]}/>}
