"use client";

import { useState } from "react";
import type { AdminSnapshot, Profile } from "@/lib/supabase/types";
import type { AdminOperationsData } from "@/lib/data/admin";
import { signOutAction } from "@/app/auth/actions";
import { createClientProject, createInvoice, createMilestone, publishProjectFile, updateBriefStatus, updateInvoiceStatus, updateMilestoneStatus, updateProductStatus, updateProjectStatus, updateTicketStatus, updateUserRole } from "@/app/admin/actions";

const sections = ["overview","products","leads","projects","users","support"] as const;
type Section = (typeof sections)[number];
const briefStatuses = ["new","reviewing","qualified","quoted","won","lost","archived"];
const productStatuses = ["draft","active","archived"];
const ticketStatuses = ["open","in_progress","waiting_customer","resolved","closed"];
const projectStatuses = ["lead","discovery","strategy","design","development","review","launch","complete","on_hold"];
const milestoneStatuses = ["upcoming","active","review","approved","complete","blocked"];
const invoiceStatuses = ["draft","issued","part_paid","paid","overdue","cancelled","refunded"];
const appRoles = ["customer","member","client","content_manager","admin"];

export function AdminDashboard({ snapshot, operations, profile, configured }: { snapshot: AdminSnapshot; operations: AdminOperationsData; profile?: Profile | null; configured: boolean }) {
  const [section, setSection] = useState<Section>("overview");
  const [projectId, setProjectId] = useState(operations.projects[0]?.id || "");
  const selectedProject = operations.projects.find(p => p.id === projectId) || operations.projects[0];
  const selectedClient = selectedProject ? operations.profiles.find(p => p.id === selectedProject.client_id) : null;
  const projectMilestones = selectedProject ? operations.milestones.filter(m => m.project_id === selectedProject.id) : [];
  const projectInvoices = selectedProject ? operations.invoices.filter(i => i.project_id === selectedProject.id) : [];
  const projectFiles = selectedProject ? operations.files.filter(f => f.project_id === selectedProject.id) : [];

  return <div className="admin-shell">
    <aside className="admin-sidebar"><div className="admin-brand"><span>JP</span><div><b>JASONPRO</b><small>CONTROL SYSTEM</small></div></div><nav>{sections.map((item,index)=><button key={item} className={section===item?"active":""} onClick={()=>setSection(item)}><span>{String(index+1).padStart(2,"0")}</span>{item.toUpperCase()}</button>)}</nav><div className="admin-env"><i/><span>{configured?"SUPABASE CONNECTED":"BACKEND FOUNDATION"}</span><small>{configured?"Live protected operations are enabled.":"Backend configuration required."}</small></div></aside>
    <section className="admin-main"><header className="admin-topbar"><div><small>ADMIN / {section.toUpperCase()}</small><h1>{section==="overview"?"Operating overview.":section.charAt(0).toUpperCase()+section.slice(1)}</h1></div><div className="admin-user"><span>{profile?.role?.toUpperCase()||"ADMIN ACCESS"}</span><b>{profile?.email||"AUTH REQUIRED"}</b>{configured&&<form action={signOutAction}><button>SIGN OUT</button></form>}</div></header>

    {section==="overview"&&<><div className="admin-metrics">{[["Products",snapshot.products],["Orders",snapshot.orders],["Project briefs",snapshot.briefs],["Active projects",snapshot.activeProjects],["Members",snapshot.members]].map(([label,value])=><article key={String(label)}><small>{label}</small><strong>{value??"—"}</strong><span>LIVE PROTECTED DATA</span></article>)}</div><div className="admin-grid"><article className="admin-panel"><span>OPERATIONS</span><h2>Lead, catalogue, project, user and support controls are live.</h2><p>Projects now include milestones, invoices and private client file publishing.</p></article><article className="admin-panel"><span>ACCESS</span><h2>Role protected.</h2><p>Database RLS remains the enforcement layer; UI visibility is not treated as security.</p></article></div></>}

    {section==="products"&&<div className="admin-module"><span>CATALOGUE</span><h2>Public product status.</h2>{operations.products.length?<div className="portal-list">{operations.products.map(p=><article key={p.id}><div><b>{p.name}</b><small>{p.category} · {p.price_label||"Admin managed pricing"}</small></div><form action={updateProductStatus}><input type="hidden" name="id" value={p.id}/><select name="status" defaultValue={p.status}>{productStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button>UPDATE</button></form></article>)}</div>:<div className="admin-empty"><strong>NO PRODUCTS</strong></div>}</div>}

    {section==="leads"&&<div className="admin-module"><span>PROJECT BRIEFS</span><h2>Incoming website leads.</h2>{operations.briefs.length?<div className="portal-list">{operations.briefs.map(b=><article key={b.id}><div><b>{b.full_name}</b><span>{b.email}</span><small>{b.service} · {new Date(b.created_at).toLocaleDateString()}</small></div><form action={updateBriefStatus}><input type="hidden" name="id" value={b.id}/><select name="status" defaultValue={b.status}>{briefStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button>UPDATE</button></form></article>)}</div>:<div className="admin-empty"><strong>NO PROJECT BRIEFS YET</strong><span>New contact-form submissions will appear here.</span></div>}</div>}

    {section==="projects"&&<div className="admin-module"><span>CLIENT DELIVERY</span><h2>Projects, milestones, invoices and files.</h2>
      <div className="admin-grid"><article className="admin-panel"><span>NEW PROJECT</span><form action={createClientProject} className="project-brief-form"><label>Client<select name="client_id" required defaultValue=""><option value="" disabled>Select account</option>{operations.profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||p.id} · {p.role}</option>)}</select></label><label>Project name<input name="name" required minLength={3}/></label><label>Summary<textarea name="summary" rows={4}/></label><button>CREATE PROJECT</button></form></article>
      <article className="admin-panel"><span>PROJECT SELECTOR</span>{operations.projects.length?<><select value={selectedProject?.id||""} onChange={e=>setProjectId(e.target.value)}>{operations.projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.status}</option>)}</select>{selectedProject&&<form action={updateProjectStatus}><input type="hidden" name="id" value={selectedProject.id}/><select name="status" defaultValue={selectedProject.status}>{projectStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button>UPDATE PROJECT STATUS</button></form>}</>:<p>No client projects yet.</p>}</article></div>

      {selectedProject&&<><div className="admin-grid"><article className="admin-panel"><span>MILESTONES</span><form action={createMilestone} className="project-brief-form"><input type="hidden" name="project_id" value={selectedProject.id}/><label>Title<input name="title" required minLength={2}/></label><label>Due date<input type="datetime-local" name="due_at"/></label><button>ADD MILESTONE</button></form>{projectMilestones.length?<div className="portal-list">{projectMilestones.map(m=><article key={m.id}><div><b>{m.title}</b><small>{m.due_at?new Date(m.due_at).toLocaleDateString():"No due date"}</small></div><form action={updateMilestoneStatus}><input type="hidden" name="id" value={m.id}/><select name="status" defaultValue={m.status}>{milestoneStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button>UPDATE</button></form></article>)}</div>:<p>No milestones yet.</p>}</article>
      <article className="admin-panel"><span>INVOICES</span><form action={createInvoice} className="project-brief-form"><input type="hidden" name="project_id" value={selectedProject.id}/><input type="hidden" name="client_id" value={selectedProject.client_id}/><label>Invoice number<input name="invoice_number" required placeholder="JPS-2026-001"/></label><label>Total amount (BWP)<input name="total_amount" type="number" min="0" step="0.01" required/></label><label>Due date<input name="due_at" type="datetime-local"/></label><button>CREATE INVOICE</button></form>{projectInvoices.length?<div className="portal-list">{projectInvoices.map(i=><article key={i.id}><div><b>{i.invoice_number}</b><span>{i.currency} {Number(i.total_amount).toFixed(2)}</span><small>{i.due_at?new Date(i.due_at).toLocaleDateString():"No due date"}</small></div><form action={updateInvoiceStatus}><input type="hidden" name="id" value={i.id}/><select name="status" defaultValue={i.status}>{invoiceStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button>UPDATE</button></form></article>)}</div>:<p>No invoices yet.</p>}</article></div>

      <div className="admin-grid"><article className="admin-panel"><span>CLIENT FILES</span><form action={publishProjectFile} encType="multipart/form-data" className="project-brief-form"><input type="hidden" name="project_id" value={selectedProject.id}/><label>Visibility<select name="visibility" defaultValue="client"><option value="client">Client visible</option><option value="internal">Internal only</option></select></label><label>File<input type="file" name="file" required/></label><button>PUBLISH FILE</button></form><small>Maximum file size: 20 MB. Client files are delivered through signed private URLs.</small></article>
      <article className="admin-panel"><span>PUBLISHED FILES</span>{projectFiles.length?<div className="portal-list">{projectFiles.map(f=><article key={f.id}><div><b>{f.file_name}</b><span>{f.visibility}</span><small>{f.byte_size?`${Math.ceil(f.byte_size/1024)} KB`:"Size unavailable"}</small></div></article>)}</div>:<p>No files published yet.</p>}</article></div>
      <div className="admin-panel"><span>CLIENT</span><h2>{selectedClient?.full_name||selectedClient?.email||"Assigned account"}</h2><p>{selectedProject.summary||"No project summary yet."}</p></div></>}
    </div>}

    {section==="users"&&<div className="admin-module"><span>ACCOUNTS + ROLES</span><h2>Control application access.</h2>{operations.profiles.length?<div className="portal-list">{operations.profiles.map(p=><article key={p.id}><div><b>{p.full_name||p.email||"Unnamed account"}</b><span>{p.company_name||p.email}</span><small>{new Date(p.created_at).toLocaleDateString()}</small></div>{p.id===profile?.id?<strong>YOUR ADMIN ACCOUNT</strong>:<form action={updateUserRole}><input type="hidden" name="id" value={p.id}/><select name="role" defaultValue={p.role}>{appRoles.map(r=><option key={r} value={r}>{r}</option>)}</select><button>UPDATE</button></form>}</article>)}</div>:<div className="admin-empty"><strong>NO ACCOUNTS</strong></div>}</div>}

    {section==="support"&&<div className="admin-module"><span>CLIENT SUPPORT</span><h2>Support queue.</h2>{operations.tickets.length?<div className="portal-list">{operations.tickets.map(t=><article key={t.id}><div><b>{t.subject}</b><span>{t.priority}</span><small>{new Date(t.created_at).toLocaleDateString()}</small></div><form action={updateTicketStatus}><input type="hidden" name="id" value={t.id}/><select name="status" defaultValue={t.status}>{ticketStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button>UPDATE</button></form></article>)}</div>:<div className="admin-empty"><strong>NO SUPPORT TICKETS</strong><span>Client portal requests will appear here.</span></div>}</div>}
    </section>
  </div>;
}
