import type { Metadata } from "next";
import PolicyPage from "@/components/PolicyPage";

export const metadata: Metadata = { title: "Privacy Notice", description: "How JasonPro Solutions handles personal information submitted through its website, project forms, accounts and client services." };

export default function PrivacyPage(){return <PolicyPage title="Privacy Notice" updated="20 August 2026" summary="This notice explains what personal information JasonPro Solutions collects through the website, why it is used, how it is protected and what choices you have." sections={[
  {title:"Information we collect",paragraphs:["JasonPro may collect information you submit directly through project enquiries, quotation requests, consultation requests, account registration, support requests and client-service workflows."],bullets:["Name, email address, telephone/WhatsApp number and company details.","Project requirements, service interests, budget context, deadlines and consultation preferences.","Account, project, invoice, file and support information where the client portal is used.","Technical information necessary to operate, secure and improve the website and connected services."]},
  {title:"How information is used",paragraphs:["Information is used only for legitimate business purposes connected with responding to enquiries, delivering requested services, operating client accounts, maintaining records, protecting the service and improving customer experience."],bullets:["Respond to project, quote and consultation enquiries.","Provide and administer services, projects and client workspaces.","Maintain operational, financial and support records.","Detect abuse, secure accounts and troubleshoot the service.","Communicate about an existing enquiry, project or account."]},
  {title:"Sharing and service providers",paragraphs:["JasonPro does not sell personal information. Information may be processed by service providers required to operate the website and business systems, such as hosting, database, email, file-storage, analytics or payment providers when those services are enabled."],bullets:["Providers should receive only the information reasonably required for their role.","Payment card information will not be collected directly by JasonPro unless an appropriate compliant payment arrangement is implemented.","Information may also be disclosed where required by applicable law or a lawful authority."]},
  {title:"Storage and security",paragraphs:["Reasonable technical and organisational controls are used to restrict access to customer and client information. Sensitive client files are intended to use private storage and access controls rather than public file links.","No internet service can promise absolute security. JasonPro therefore limits collection to information that has a business purpose and reviews access as systems evolve."]},
  {title:"Retention",paragraphs:["Information is retained only for as long as it is reasonably required for the enquiry, client relationship, operational record, legal obligation, dispute resolution or security purpose for which it was collected. Retention periods may differ by record type."]},
  {title:"Your choices",paragraphs:["You may request access to, correction of or deletion of personal information held by JasonPro where applicable and where retention is not required for a legitimate legal or business reason."],bullets:["Ask what personal information is held about you.","Request correction of inaccurate information.","Request deletion where there is no continuing lawful or operational requirement to retain it.","Withdraw optional marketing consent if marketing communications are introduced."]},
  {title:"Contact",paragraphs:["Privacy questions or requests can be sent to Marupingjason@gmail.com or directed to JasonPro Solutions in Gaborone, Botswana. Identity verification may be required before releasing or changing account-related information."]},
]}/>}
