import type { Metadata } from "next";
import PolicyPage from "@/components/PolicyPage";

export const metadata: Metadata = { title: "Refund & Cancellation Policy", description: "How JasonPro Solutions handles service cancellations, deposits, digital products and custom production orders." };

export default function RefundPage(){return <PolicyPage title="Refund & Cancellation" updated="20 August 2026" summary="Because JasonPro provides a mix of professional services, digital work and custom production, cancellation and refund treatment depends on what has already been committed, produced or delivered." sections={[
  {title:"Professional services",paragraphs:["Project deposits reserve capacity and allow work to begin. If a client cancels after work has started, fees already earned for discovery, design, development, administration, third-party costs or other completed work are generally not refundable."],bullets:["Any unearned balance should be assessed against the agreed scope and work completed.","Third-party costs already committed on the client’s behalf may be non-refundable.","A project-specific agreement or quotation takes priority where it contains more specific cancellation terms."]},
  {title:"Custom print and physical production",paragraphs:["Custom items are produced to client specifications and may become non-refundable once artwork is approved, materials are ordered or production has begun. JasonPro should confirm proof approval before material custom production where practical."],bullets:["Report production defects or incorrect fulfilment promptly with supporting photographs or details.","Approved artwork errors, incorrect client-supplied specifications or normal production tolerances are assessed differently from manufacturing defects."]},
  {title:"Digital products",paragraphs:["Digital products are not currently sold through an active automated payment checkout on this website. When paid digital delivery is introduced, product-specific licence, delivery and refund terms will be shown before purchase."]},
  {title:"Appointments and consultations",paragraphs:["If a paid consultation service is introduced, rescheduling and cancellation rules will be disclosed before booking. For currently unpaid consultation requests, please notify JasonPro as early as possible if an agreed meeting can no longer be attended."]},
  {title:"How to request a review",paragraphs:["Send the project or order reference, your name, the reason for the request and any relevant evidence to Marupingjason@gmail.com. Refund or cancellation decisions should be based on the agreed scope, work completed, costs already incurred and applicable law rather than an automatic one-rule-for-all policy."]},
]}/>}
