import type { Metadata } from "next";
import Link from "next/link";
import InteriorHeader from "@/components/InteriorHeader";

export const metadata: Metadata = {
  title: "Frequently Asked Questions | JasonPro Solutions",
  description: "Answers about JasonPro Solutions projects, websites, systems, branding, timelines, pricing, support and working process.",
};

const faqs=[
  ["What does JasonPro Solutions specialise in?","The primary focus is web design and development, business systems and SaaS, graphic design and brand identity, and practical automation/intelligence. JasonPro also supports photography, business administration, vehicle sourcing and custom branded clothing."],
  ["Do you only build normal business websites?","No. Projects can range from a focused commercial website to authenticated web applications, client portals, dashboards, internal systems, ecommerce experiences and SaaS products. The solution should follow the business problem rather than forcing every project into the same template."],
  ["How does a new project start?","Start with the project brief. The first step is understanding what the business is trying to achieve, what is not working today, who the users are and what the finished solution needs to do. Scope, approach and quotation follow from that information."],
  ["Can you redesign an existing website?","Yes. A redesign can include positioning, information architecture, UX, visual design, frontend implementation and production hardening. The existing site should first be audited so useful content or functionality is not discarded without reason."],
  ["Can JasonPro build a business system from our current manual process?","Yes. The preferred approach is to map the current workflow first—roles, records, approvals, repeated tasks, exceptions and reporting needs—then design the system around the actual operation rather than simply digitising every manual step."],
  ["Do you provide logo design only?","A standalone mark can be part of a project, but JasonPro generally approaches branding as a system: logo, typography, colour, graphic language, applications and production-ready artwork. The exact deliverables depend on the brief."],
  ["How much does a project cost?","There is no single price for custom work because scope can vary substantially. A focused website, a client portal and a multi-role SaaS platform are different projects. Submit the brief or request a quotation so the required work can be defined before a price is presented."],
  ["How long does a project take?","Timeline depends on scope, content readiness, integrations, feedback speed and testing requirements. JasonPro does not publish a universal delivery promise for custom projects; the working timeline is agreed after scope is understood."],
  ["Do you offer maintenance after launch?","Support and maintenance can be included where the project requires ongoing updates, monitoring or operational assistance. The responsibilities, response expectations and included work should be defined rather than assumed."],
  ["Can you work with an existing brand or codebase?","Yes. Existing assets, systems and code should be audited before replacement. The goal is to retain what is useful, fix what is weak and avoid unnecessary rebuilding."],
  ["Can you integrate payments or subscriptions?","Yes, but payment processing is connected only after the provider, account, settlement requirements and production credentials are verified. Raw card data should not be stored by JasonPro systems."],
  ["How are client files and project information handled?","The JasonPro client portal uses authenticated access and private project-file storage. Client-visible files are delivered through time-limited signed links rather than exposing the storage bucket publicly."],
  ["Do you guarantee business results, sales or betting outcomes?","No. JasonPro can improve the quality of design, systems, workflows and information presentation, but no legitimate service can guarantee commercial results. Any future sports-analysis content is informational and must never be presented as guaranteed winnings."],
  ["What is the best way to know whether JasonPro is a fit?","Review the relevant service page and selected work, then submit the business problem. A good fit usually exists when the project needs design judgement, systems thinking and practical implementation to work together."],
];

export default function FaqPage(){return <main className="interior-page"><InteriorHeader/><section className="interior-hero"><span>FAQ / WORKING WITH JASONPRO</span><h1>CLARITY BEFORE<br/><em>COMMITMENT.</em></h1><p>Common questions about scope, process, pricing, systems, support and how projects are handled.</p></section><section style={{padding:"6vh 5vw 10vh",background:"#f5f5f2"}}>{faqs.map(([q,a],i)=><article key={q} style={{display:"grid",gridTemplateColumns:"70px minmax(0,1fr)",gap:"24px",padding:"32px 0",borderBottom:"1px solid #d4d4cf"}}><span style={{fontSize:"10px",color:"#d91f26",fontWeight:800}}>{String(i+1).padStart(2,"0")}</span><div><h2 style={{fontSize:"clamp(24px,3vw,44px)",letterSpacing:"-.04em",margin:"0 0 12px"}}>{q}</h2><p style={{maxWidth:"850px",color:"#555",lineHeight:1.7,margin:0}}>{a}</p></div></article>)}</section><section className="interior-end"><small>STILL NEED TO DISCUSS IT?</small><h2>START WITH THE BUSINESS PROBLEM.</h2><div style={{display:"flex",gap:"10px",flexWrap:"wrap"}}><Link href="/contact">START A PROJECT →</Link><Link href="/quote">REQUEST A QUOTE →</Link></div></section></main>}
